language: go
sudo: false
go:
  - 1.11.5

jobs:
  include:
    - stage: unit tests
      script: 
        - go test -v -covermode=count -coverprofile=coverage.out
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
      os: 
        - windows
        - Linux
      before_install:
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
    - stage: Linux release
      script: 
        - go build
        - ls
      os:  Linux
    - stage: Windows release
      script: 
      - go build
      - ls
      os:  windows
