language: go
sudo: false
os: 
  - windows
  - Linux

go:
  - 1.11.5

script: 
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - go build
  
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  
